name: 天翼云盘签到

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '30 5,17 * * *'
  workflow_dispatch:
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 打印ip地址
        run: echo "My IP address is $(curl -s ifconfig.me)"
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: 安装环境
        run: pip install -r requirements.txt
      - name: 签到
        run: |
          python3 ./main.py | tee log.md
        env:
          TYYP_USERNAME: ${{ secrets.TYYP_USERNAME }}
          TYYP_PSW: ${{ secrets.TYYP_PSW }}
      - uses: actions/checkout@v2
      - run: |
          echo "Log path is: $GITHUB_WORKSPACE/log.md"
          cp $GITHUB_WORKSPACE/log.md ./log.md
      
      - uses: actions-js/push@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          message: 'Upload log.md'
